replicaCount: 1

image:
  repository: localhost:5000/local/mm
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8000

resources:
  requests:
    cpu: "8"
  limits:
    cpu: "8"

containerPort: 8000

persistence:
  enabled: true
  size: 1Gi
  mountPath: /state
  storageClass: local-path

# TODO: metallb should be deployed separately down the road.
metallb:
  enabled: true
  ipRange: "192.168.40.220-192.168.40.240"
