replicaCount: 1

image:
  repository: mm
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000
  nodePort: 30080

resources:
  requests:
    cpu: "8"
  limits:
    cpu: "8"

containerPort: 8000

persistence:
  enabled: true
  size: 1Gi
  mountPath: /state
  storageClass: local-path
